# Generated by Django 4.2.7 on 2023-12-02 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemonapi', '0003_remove_cartitem_unit_price_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='price',
        ),
    ]
