# Generated by Django 4.2.7 on 2023-12-02 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemonapi', '0005_alter_cartitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
